services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql

  broker:
    image: eclipse-mosquitto

volumes:
  postgres_data: